---
- name: Fix CA RPC Registration
  hosts: dc
  gather_facts: no
  vars:
    ansible_user: "vagrant"
    ansible_password: "vagrant"
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
    ansible_become: yes
    ansible_become_method: runas
    ansible_become_user: "SERINI\\Administrator"
    ansible_become_password: "P@ssw0rd123!"

  tasks:
    - name: Ensure Remote Registry is running
      ansible.windows.win_service:
        name: RemoteRegistry
        state: started
        start_mode: auto

    - name: Restart Certificate Services
      ansible.windows.win_service:
        name: "CertSvc"
        state: restarted
