---
- name: Disable Firewall on DC for RPC Access
  hosts: dc
  gather_facts: no
  vars:
    ansible_user: "vagrant"
    ansible_password: "vagrant"
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
    ansible_become: yes
    ansible_become_method: runas
    ansible_become_user: "SERINI\\Administrator"
    ansible_become_password: "P@ssw0rd123!"

  tasks:
    - name: Disable Windows Firewall (All Profiles)
      ansible.windows.win_shell: Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False
