- hosts: ca
  gather_facts: no
  vars:
    ansible_user: vagrant
    ansible_password: vagrant
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
    ansible_winrm_server_cert_validation: ignore
  tasks:
    - name: Check local user
      ansible.windows.win_shell: whoami

    - name: Check Domain Admin elevation
      ansible.windows.win_shell: whoami
      become: yes
      become_method: runas
      become_user: "SERINI\\Administrator"
      vars:
        ansible_become_password: "P@ssw0rd123!"
