ansible_user: vagrant
# Update this path if you run Ansible from a different project location. Relative to ansible dir: ../vagrant/.vagrant/machines/attacker/vmware_desktop/private_key
ansible_ssh_private_key_file: ../vagrant/.vagrant/machines/attacker/vmware_desktop/private_key
