---
- name: Fix CA RPC Registration
  hosts: dc
  gather_facts: no
  become: yes
  become_method: runas
  become_user: "{{ domain_user }}"
  tasks:
    - name: Ensure Remote Registry is running
      ansible.windows.win_service:
        name: RemoteRegistry
        state: started
        start_mode: auto

    - name: Restart Certificate Services
      ansible.windows.win_service:
        name: "CertSvc"
        state: restarted
